<!--<style>-->
<!--    a:link,-->
<!--    a:visited-->
<!--    {-->
<!--        color: #0398CA;-->
<!--    }-->
<!---->
<!--    span#zf-name-->
<!--    {-->
<!--        color: #91BE3F;-->
<!--    }-->
<!---->
<!--    div#welcome-->
<!--    {-->
<!--        color: #FFFFFF;-->
<!--        background-image: url(http://framework.zend.com/images/bkg_header.jpg);-->
<!--        width:  600px;-->
<!--        height: 400px;-->
<!--        border: 2px solid #444444;-->
<!--        overflow: hidden;-->
<!--        text-align: center;-->
<!--    }-->
<!---->
<!--    div#more-information-->
<!--    {-->
<!--        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);-->
<!--        height: 100%;-->
<!--    }-->
<!--</style>-->
<!--<div id="welcome">-->
<!--    <h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>-->
<!---->
<!--    <h3>This is your project's main page</h3>-->
<!---->
<!--    <div id="more-information">-->
<!--        <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>-->
<!--        <p>-->
<!--            Helpful Links: <br />-->
<!--            <a href="http://framework.zend.com/">Zend Framework Website</a> |-->
<!--            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>-->
<!--        </p>-->
<!--    </div>-->
<!--</div>-->

<div>
    <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'set-language', 'lang'=> 'sr'));?>">Srpski</a> |
    <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'set-language', 'lang'=> 'en'));?>">English</a>
    <?php

    //    echo '<br/>';
    //    echo '<br/>';
    //    echo 'front session lang: '.$this->sess_lang;

    echo '<br/>';
    echo '<br/>';
    echo '<br/>';
    echo $this->translate->_('Prvi tekst za prevod');
    echo '<br/>';
    echo $this->translate->_('Drugi tekst za prevod');
    echo '<br/>';
    echo $this->translate->_('Treci tekst za prevod');
    echo '<br/>';
    echo $this->translate->_('Cetvrti tekst za prevod');
    echo '<br/>';
    echo $this->translate->_('Peti tekst za prevod');
    echo '<br/>';
    ?>
</div>

<?php echo $this->mess; ?>
<br/>
<?php echo $this->post; ?>