<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php $this->headLink()->appendStylesheet($this->baseUrl('css/style.css'), 'all');?>
	<?php $this->headLink()->appendStylesheet($this->baseUrl('css/jquery-ui.css'), 'all');?>

    <?php $this->headScript()->appendFile($this->baseUrl('js/jquery.min.js'));?>
    <?php $this->headScript()->appendFile($this->baseUrl('js/jquery-ui.js'));?>
    <?php $this->headScript()->appendFile($this->baseUrl('js/custom.js'));?>


    <?php echo $this->headLink();?>
    <?php echo $this->headScript();?>
</head>
<body>
<a style="float: right; margin-top: 40px;" href="logout">Logout</a>
